name: Send bulk/block Deals Notification

on: 
  schedule:
    - cron: '0 17 * * 1-5'
  # push:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Preprocessing
        run: |
          curl -L 'https://www.nseindia.com/products/dynaContent/equities/equities/bulkdeals.jsp?symbol=&segmentLink=13&symbolCount=&dateRange=day&fromDate=&toDate=&dataType=DEALS' -H 'Pragma: no-cache' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' > bulk
          grep -E 'number|normalText' bulk | awk -F'<|>' '{print $3}' | sed -e 's/BUY/Bought/' -e 's/SELL/Sold/' > bulk_deals
      - name: Running package
        env:
          FIND_FOR: ${{ secrets.FIND_FOR }}
          SENDER: ${{ secrets.SENDER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
        run: |
          python find_imp_deals.py
